In [3]:
import numpy as np

In [4]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr_2d.shape

(3, 4)

In [6]:
arr_2d.sum()

78

In [7]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [8]:
arr_2d.sum(axis=1)

array([10, 26, 42])