In [6]:
import numpy as np

In [7]:
np.random.rand(4)

array([0.89244166, 0.60863125, 0.57383911, 0.59773788])

In [8]:
np.random.rand(5,5)

array([[0.92488742, 0.50376883, 0.43504862, 0.42035138, 0.29454305],
       [0.28094849, 0.29188762, 0.27657678, 0.00567892, 0.39591835],
       [0.30427314, 0.22032499, 0.79949834, 0.97797644, 0.68888931],
       [0.97561665, 0.09296974, 0.18071824, 0.49897824, 0.76137162],
       [0.29763825, 0.20336656, 0.12513761, 0.08680562, 0.45493289]])

In [9]:
np.random.randn(10)

array([-0.64810385, -0.76972216,  0.90786116, -1.19108055, -1.62234364,
       -0.49936691, -0.87347918, -1.28809273, -0.40327538,  0.27328032])

In [12]:
np.random.randint(1, 100)

68

In [13]:
np.random.randint(1, 100, 10)

array([70, 88,  4, 25, 59,  4, 24, 47, 73, 67])

In [15]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [16]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [17]:
arr = np.arange(25)

In [18]:
arr.shape

(25,)

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([23,  2, 21,  1, 23, 43, 29, 37,  1, 20])

In [23]:
ranarr.max()

43

In [24]:
ranarr.min()

1

In [25]:
ranarr.argmax()

5

In [26]:
ranarr.argmin()

3

In [27]:
ranarr.dtype

dtype('int64')